config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  get "/projects" => "projects#index", :as => 'projects'
  get "/projects/:id" => "projects#show"
end

app/models/github_api.rb
require 'faraday'
require 'json'

class GithubApi
  attr_reader :tracker_comments

  def initialize (tracker_comments)
    @tracker_comments = tracker_comments
  end

  def comments
    relevent_comments = tracker_comments.select { |comment| comment.has_key?("text") && comment["text"].include?("Commit by") }
    relevent_comments.each_with_object([]) do |comment, comments_array|
      body_parsed = comment['text'].split('/')
      git_username = body_parsed[3]
      git_repo = body_parsed[4]
      git_sha = comment["commit_identifier"]

      response = connect("/repos/#{git_username}/#{git_repo}/commits/#{git_sha}/comments")
      comments_array.concat(JSON.parse(response.body))
    end
  end

  private

  def connect(url)
    faraday = Faraday.new(:url => "https://api.github.com") do |f|
      f.adapter(Faraday.default_adapter)
      f.basic_auth(ENV['GITHUB_USERNAME'], ENV['GITHUB_PASSWORD'])
    end
    faraday.get(url)
  end
end

app/models/tracker_api.rb
require 'faraday'
require 'json'

class TrackerApi
  attr_reader :token

  def initialize(token)
    @token = token
  end

  def projects
    api_call
  end

  def stories(project_id)
    api_call("/#{project_id}/stories")
  end

  def comments(project_id)
    stories(project_id).each_with_object([]) do |story, comments|
      comments.concat api_call("/#{project_id}/stories/#{story["id"]}/comments")
    end
  end

  private

  def api_call(url='')
    response = Faraday.get('https://www.pivotaltracker.com/services/v5/projects' + url, {}, 'X-TrackerToken' => token)
    JSON.parse(response.body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    tracker = TrackerApi.new(ENV['TRACKER_TOKEN'])

    @projects = tracker.projects
  end

  def show
    tracker = TrackerApi.new(ENV['TRACKER_TOKEN'])
    @stories = tracker.stories(params[:id])
    @comments = tracker.comments(params[:id])
    github = GithubApi.new(@comments)
    @github_comments = github.comments
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TrackerhubApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/index.html.erb
<ul>
  <% @projects.each do |project| %>
    <li><a href="projects/<%= project['id'] %>"><%= project['name'] %></a></li>
  <% end %>
</ul>

app/views/projects/show.html.erb
<h2>Stories</h2>
<ul>
  <% @stories.each do |story| %>
    <li><%= story["name"] %></li>
  <% end %>
</ul>
<hr>

<h2>Tracker Comments</h2>
<ul>
  <% @comments.each do |comment| %>
    <li><%= comment["text"] %></li>
  <% end %>
</ul>
<hr>

<h2>Github Comments</h2>
<ul>
  <% @github_comments.each do |comment| %>
    <li><%= comment["body"] %></li>
  <% end %>
</ul>
<hr>

app/views/welcome/index.html.erb
<%= link_to 'View projects', projects_path %>